### ISSUE TITLE
Desktop linux version (Gramax_2025.5.22-linux.71.AppImage) can't export to pdf or docx

### ISSUE THREAD

**Issue by kudryashovda** [Gram-ax/gramax#194]
### Describe the bug

Export any article or catalog to pdf or docx leads to a freezed window with "Generating PDF" followed "Gramax is not responding" (Force quit or wait).

I have no git account connected to the app and I cleaned my workspace.yaml file to:
```
name: Default Workspace
icon: layers
groups: null
enterprise:
  gesUrl: null
  lastUpdateDate: null
services:
  gitProxy:
    url: null
  auth:
    url: null
  diagramRenderer:
    url: null
  review:
    url: null
  cloud:
    url: null
```

OS: Ubuntu 24.04.2 LTS
App: Gramax_2025.5.22-linux.71.AppImage
To hide some warnings in console I removed some libs from the App (https://github.com/Gram-ax/gramax/issues/189#issuecomment-2905629584). But on default installation I also can't export to the formats.
